harness:
  subdomain: idp-arc
  secured: false

  service:
    port: 8080
    auto: true

  deployment:
    auto: true
    port: 8080
    resources:
      requests:
        memory: 512Mi
        cpu: 125m
      limits:
        memory: 512Mi

  dependencies:
    build:
      - cloudharness-base
      - cloudharness-frontend-build

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
