name: Run ESLint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: applications/idp-arc/frontend/yarn.lock

    - name: Install dependencies
      working-directory: applications/idp-arc/frontend
      run: yarn install --frozen-lockfile

    - name: Run ESLint
      working-directory: applications/idp-arc/frontend
      run: yarn lint